kind: ConfigMap 
apiVersion: v1 
metadata:
  name: mssql
data:
  mssql.conf: |
    [EULA]
    accepteula = Y
    accepteulaml = Y
    
    [coredump]
    captureminiandfull = true
    coredumptype = full
    
    [hadr]
    hadrenabled = 1
    
    [language]
    lcid = 1033
  